name: Version Change Action

on:
  push:
    paths:
      - version.json  # Trigger on changes to version.json

jobs:
  run-on-version-change:
    runs-on: windows-latest  # Use Windows 10 runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5 requests pywin32 pyinstaller pillow  # Install specific dependencies

    - name: Create actions-temp folder
      run: |
        mkdir actions-temp  # Create the folder called actions-temp

    - name: Download picoBuild.py script
      run: |
        curl -L -o actions-temp/picoBuild.py https://raw.githubusercontent.com/nixietab/picodulce-build-script/refs/heads/main/picoBuild.py

    - name: Run picoBuild.py script
      run: |
        python actions-temp/picoBuild.py
